env: production
isProduction: true
mongodb:
  url: mongodb://vaporeon.internal.kipapp.co/foundry
  backuphost: jankeon.internal.kipapp.co
  options:
    replset:
      rs_name: foundry
      socketOptions:
        keepAlive: 1
elasticsearch:
  url: http://elasticsearch-cerulean.internal.kipapp.co:9200
elasticsearchElk:
  url: http://elasticsearch-cerulean.internal.kipapp.co:9200
redis:
  port: 6379
  url: redis-thunder.internal.kipapp.co
geoipURL: http://localhost:8080/json/
neighborhoodServer:
  url: http://localhost:9998
app:
  publicAPI: https://kipapp.co/styles/api
